# set(CMAKE_FIND_LIBRARY_SUFFIXES .a ${CMAKE_FIND_LIBRARY_SUFFIXES})

find_library(
  CGNS_LIBRARY
  NAMES cgns
  PATHS ${PROJECT_SOURCE_DIR}/ext/CGNS-4.4.0/lib
)

find_path(
  CGNS_INCLUDE_DIR
  NAMES cgnslib.h
  PATHS ${PROJECT_SOURCE_DIR}/ext/CGNS-4.4.0/include
)

if(CGNS_LIBRARY AND CGNS_INCLUDE_DIR)
  set(CGNS_FOUND TRUE)
  set(CGNS_LIBRARY ${CGNS_LIBRARY})
  set(CGNS_INCLUDE_DIR ${CGNS_INCLUDE_DIR})
else()
  set(CGNS_FOUND FALSE)
endif()
