set(CMAKE_FIND_LIBRARY_SUFFIXES .a ${CMAKE_FIND_LIBRARY_SUFFIXES})

find_library(
  HDF5_LIBRARY
  NAMES hdf5
  PATHS ${PROJECT_SOURCE_DIR}/ext/HDF5-1.10.10/lib
)

find_library(
  HDF5_FORTRAN_LIBRARY
  NAMES hdf5_fortran
  PATHS ${PROJECT_SOURCE_DIR}/ext/HDF5-1.10.10/lib
)

find_path(
  HDF5_INCLUDE_DIR
  NAMES H5Library.h
  PATHS ${PROJECT_SOURCE_DIR}/ext/HDF5-1.10.10/include
)

if(HDF5_LIBRARY AND HDF5_INCLUDE_DIR)
  set(HDF5_FOUND TRUE)
  set(HDF5_LIBRARY ${HDF5_LIBRARY} ${HDF5_FORTRAN_LIBRARY})
  set(HDF5_INCLUDE_DIR ${HDF5_INCLUDE_DIR})
else()
  set(HDF5_FOUND FALSE)
endif()
