# set(CMAKE_FIND_LIBRARY_SUFFIXES .a ${CMAKE_FIND_LIBRARY_SUFFIXES})

set(GKLIB_ROOT ${PROJECT_SOURCE_DIR}/ext/METIS-5.2.1)

find_path(
  GKLIB_INCLUDE_PATH
  NAMES GKlib.h
  PATHS ${GKLIB_ROOT}/include
)

find_library(
  GKLIB_LIBRARY
  NAMES GKlib
  PATHS ${GKLIB_ROOT}/lib
  NO_DEFAULT_PATH
)

if(GKLIB_INCLUDE_PATH AND GKLIB_LIBRARY)
  set(GKLIB_FOUND TRUE)
  set(GKLIB_LIBRARY ${GKLIB_LIBRARY})
  set(GKLIB_INCLUDE_PATH ${GKLIB_INCLUDE_PATH})
else()
  set(GKLIB_FOUND FALSE)
endif()
