# set(CMAKE_FIND_LIBRARY_SUFFIXES .a ${CMAKE_FIND_LIBRARY_SUFFIXES})

set(METIS_ROOT ${PROJECT_SOURCE_DIR}/ext/METIS-5.2.1)

find_path(
  METIS_INCLUDE_PATH
  NAMES metis.h
  PATHS ${METIS_ROOT}/include
)

find_library(
  METIS_LIBRARY
  NAMES metis
  PATHS ${METIS_ROOT}/lib
  NO_DEFAULT_PATH
)

if(METIS_INCLUDE_PATH AND METIS_LIBRARY)
  set(METIS_FOUND TRUE)
  set(METIS_LIBRARY ${METIS_LIBRARY})
  set(METIS_INCLUDE_PATH ${METIS_INCLUDE_PATH})
else()
  set(METIS_FOUND FALSE)
endif()
